(function(){
  "use strict";
  var root=document.getElementById('venue-detail');
  if(!root)return;
  var params=new URLSearchParams(location.search),id=params.get('id')||'',requested=params.get('name')||'';
  function esc(value){return String(value==null?'':value).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
  function normalize(value){return String(value||'').replace(/\u00a0/g,' ').replace(/^(東京都|神奈川県|千葉県|埼玉県|北海道|京都府|大阪府|.{2,3}県)\s*/,'').replace(/[\s　]+/g,'').replace(/[（(][^）)]*(?:都|道|府|県|市|区)[^）)]*[）)]$/g,'').replace(/大ホール/g,'').toLowerCase()}
  function names(event){var out=[];(event.schedule||[]).forEach(function(item){if(item&&item.venue)out.push({date:item.date,venue:item.venue})});if(!out.length&&event.venue&&!/複数会場|オンライン/.test(event.venue))out.push({date:event.eventDate,venue:event.venue});return out}
  function occursAt(event,venue){var keys=[venue.name].concat(venue.aliases||[]).map(normalize);return names(event).some(function(item){var n=normalize(item.venue);return keys.some(function(k){return n===k||n.indexOf(k)>=0||k.indexOf(n)>=0})})}
  function fmt(value){var m=String(value||'').match(/^(\d{4})-(\d{2})-(\d{2})/);return m?(+m[1])+'/'+(+m[2])+'/'+(+m[3]):'日程未定'}
  function title(event){return String(event.eventTitle||event.title||'KAWAII LAB. 公演').replace(/^(FRUITS ZIPPER|CANDY TUNE|SWEET STEADY|CUTIE STREET|MORE STAR)\s*/,'')}
  function inferFallback(name){var m=String(name||'').match(/北海道|東京都|京都府|大阪府|.{2,3}県/);var prefecture=m?m[0]:'';var clean=String(name||'').replace(/^\S+[都道府県]\s*/,'').trim()||name||'会場';return{id:'',name:clean,aliases:[name],prefecture:prefecture||'所在地確認中',area:'',type:'ライブ会場',scale:'公演形式により変動',address:'詳細情報を整理中です',access:['公演主催者または会場公式サイトの最新案内を確認してください。'],capacityNote:'公演形式により変動',officialUrl:'',mapUrl:'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(name||clean),tips:['開場・開演時刻と入場方法を公演公式ページで確認してください。','帰りの交通手段と終電時刻を事前に確認しておくと安心です。'],provisional:true}}
  function render(venue,events){document.title=venue.name+'｜会場ガイド｜KAWAII LAB.同好会';var upcoming=[];events.forEach(function(event){if(!occursAt(event,venue))return;names(event).forEach(function(item){var keys=[venue.name].concat(venue.aliases||[]).map(normalize),n=normalize(item.venue);if(keys.some(function(k){return n===k||n.indexOf(k)>=0||k.indexOf(n)>=0}))upcoming.push({date:item.date,title:title(event),group:event.group,url:event.url||''})})});upcoming.sort(function(a,b){return String(a.date).localeCompare(String(b.date))});var access=(venue.access||[]).map(function(x){return'<li>'+esc(x)+'</li>'}).join('');var tips=(venue.tips||[]).map(function(x){return'<li>'+esc(x)+'</li>'}).join('');var eventHtml=upcoming.length?upcoming.map(function(x){return'<div class="venue-upcoming-item"><time datetime="'+esc(x.date)+'">'+esc(fmt(x.date))+'</time><div><span class="venue-badge">'+esc(x.group||'KAWAII LAB.')+'</span><br>'+(x.url?'<a href="'+esc(x.url)+'" target="_blank" rel="noopener">'+esc(x.title)+' →</a>':esc(x.title))+'</div></div>'}).join(''):'<p class="venue-upcoming-empty">現在のスケジュールに、この会場の公演は掲載されていません。</p>';root.innerHTML='<nav class="venue-breadcrumb" aria-label="パンくず"><a href="index.html">トップ</a><span>›</span><a href="venues.html">会場ガイド</a><span>›</span><span>'+esc(venue.name)+'</span></nav><section class="venue-detail-hero"><p class="venue-detail-kicker">VENUE GUIDE</p><h1>'+esc(venue.name)+'</h1><p class="venue-detail-sub">'+esc(venue.prefecture)+(venue.area?'・'+esc(venue.area):'')+'｜'+esc(venue.type||'ライブ会場')+'</p></section><div class="venue-detail-grid"><section class="venue-info-card"><h2>📍 基本情報</h2><dl class="venue-facts"><div><dt>住所</dt><dd>'+esc(venue.address||'公式案内を確認')+'</dd></div><div><dt>会場タイプ</dt><dd>'+esc(venue.type||'ライブ会場')+'・'+esc(venue.scale||'')+'</dd></div><div><dt>規模の目安</dt><dd>'+esc(venue.capacityNote||'公演形式により変動')+'</dd></div></dl><div class="venue-actions">'+(venue.officialUrl?'<a class="venue-action" href="'+esc(venue.officialUrl)+'" target="_blank" rel="noopener">公式サイト ↗</a>':'')+'<a class="venue-action secondary" href="'+esc(venue.mapUrl)+'" target="_blank" rel="noopener">地図を開く ↗</a></div>'+(venue.provisional?'<p class="venue-provisional"><strong>情報更新中：</strong>この会場は基本情報を整理中です。来場前に必ず公演主催者の最新案内をご確認ください。</p>':'')+'</section><section class="venue-info-card"><h2>🚉 アクセス</h2><ul class="venue-access-list">'+access+'</ul></section><section class="venue-info-card wide"><h2>💡 はじめて行くときのメモ</h2><ul class="venue-tip-list">'+tips+'</ul></section><section class="venue-info-card wide"><h2>🎤 掲載中の公演</h2><div class="venue-upcoming">'+eventHtml+'</div></section></div>'}
  Promise.all([fetch('./data/venues.json',{cache:'no-store'}).then(function(r){return r.json()}),fetch('./data/live-events.json',{cache:'no-store'}).then(function(r){return r.json()}).catch(function(){return{events:[]}})]).then(function(values){var venues=values[0].venues||[],venue=venues.find(function(v){if(id&&v.id===id)return true;if(!requested)return false;var n=normalize(requested);return [v.name].concat(v.aliases||[]).some(function(x){var k=normalize(x);return n===k||n.indexOf(k)>=0||k.indexOf(n)>=0})});venue=venue||inferFallback(requested);render(venue,values[1].events||[])}).catch(function(){root.innerHTML='<div class="venue-empty">会場情報を読み込めませんでした。<br><a href="venues.html">会場一覧へ戻る</a></div>'});
})();

