const core=require('../route-core.js');

const S=(id,name,railways)=>({'owl:sameAs':id,'odpt:stationTitle':{ja:name},'odpt:railway':railways});
const R=(id,name,operator,stations)=>({'owl:sameAs':id,'odpt:railwayTitle':{ja:name},'odpt:operator':operator,'odpt:stationOrder':stations.map((station,index)=>({'odpt:index':index,'odpt:station':station}))});
const A='odpt.Railway:Test.A';
const B='odpt.Railway:Test.B';
const C='odpt.Railway:Test.C';
const A0='odpt.Station:Test.A.A0';
const X='odpt.Station:Test.X.X';
const Y='odpt.Station:Test.Y.Y';
const D='odpt.Station:Test.C.D';
const payload={Station:[S(A0,'A0',[A]),S(X,'X',[A,B]),S(Y,'Y',[B,C]),S(D,'D',[C])],Railway:[R(A,'A線','op:A',[A0,X]),R(B,'B線','op:B',[X,Y]),R(C,'C線','op:C',[Y,D])],TrainType:[]};
const model=core.createModel([payload]);
const path=model.shortestPath(model.resolveInput('A0').group,model.resolveInput('D').group);
if(!path)throw new Error('Synthetic path was not created');
const exact=(railway,stations,number,timetableId,departure,arrival,destinationId)=>({version:1,railway,timeBasis:'train-timetable',stations,calendars:['weekday'],trainTypes:['odpt.TrainType:Test.Local'],trips:[[0,0,number,[[0,null,departure],[1,arrival,null]],destinationId,'train:'+number,timetableId]]});
const tables={};
tables[A]=exact(A,[A0,X],'777','tt:A',600,605,D);
tables[B]=exact(B,[X,Y],'777','tt:B',610,615,D);
tables[C]=exact(C,[Y,D],'777','tt:C',620,625,D);
const ordinary=model.timedItinerary(path,tables,600,'weekday',5,null,null);
if(!ordinary)throw new Error('Ordinary itinerary missing');
if(ordinary.transfers!==2)throw new Error(`Same train number alone must not remove transfers: ${ordinary.transfers}`);
const links=new Map([[[`tt:tt:A`,A,B].join('\u0001'),new Set(['tt:tt:B'])],[[`tt:tt:B`,B,C].join('\u0001'),new Set(['tt:tt:C'])]]);
const resolver=(identityKey,fromRailway,toRailway)=>links.get([identityKey,fromRailway,toRailway].join('\u0001'))||null;
const through=model.timedItinerary(path,tables,600,'weekday',5,null,resolver);
if(!through)throw new Error('Strict through itinerary missing');
if(through.transfers!==0)throw new Error(`Expected 0 transfers with explicit same-train edges, got ${through.transfers}`);
if(!through.segments[1].throughFromPrevious||!through.segments[2].throughFromPrevious)throw new Error('Explicit same-train boundaries were not marked through');
if(through.segments[1].identityKey!=='tt:tt:B'||through.segments[2].identityKey!=='tt:tt:C')throw new Error('Timetable identity was not propagated');
console.log('cross-operator strict same-train test passed');
